[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = [
  "npm run build:backend",
  "cd frontend && GENERATE_SOURCEMAP=false npm run build"
]

[start]
cmd = "node dist/server.js"

[variables]
NODE_OPTIONS = "--max-old-space-size=460"
